#!/usr/bin/env bash
# Configures a new Ubuntu machine to respect above requirementsdd

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i “0,/location \/ {/s//location \/ {\n\t\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-available/default
sudo service nginx restart
