#!/usr/bin/env bash
# Install  load balancer

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0

sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*
echo -e "frontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "backend backendnodes\n\tbalance roundrobin\n\tserver 772-web-01 35.237.198.149 check\n\tserver 772-web-02 35.227.117.187 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
