#!/usr/bin/env bash
# Displays Process and PID file.
echo $$ > /var/run/holbertonscript.pid
while ((1))
do
	trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT
	echo "To infinity and beyond"
	sleep 2
done
