#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes

h=0
m=1
while [ $h -le 12 ]
do
	echo "Hour: $h"
	while [ $m -le 59 ]
	do
		echo "$m"
		((m++))
	done
	((h++))
	m=1
done
