#!/usr/bin/env bash
# Runs as nginx user
pkill apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 766 /etc/nginx/nginx.conf
sudo sed -i 's:80:8080:' /etc/nginx/sites-available/default
sudo -u nginx service nginx start